name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment:
      name: DEV
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: us-east-1
          mask-aws-account-id: true
          audience: sts.amazonaws.com
          role-session-name: terraform-deployment-gaestebuch-api

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.8.2"

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -var-file="variables.tfvars" -auto-approve
